### ISSUE TITLE
Sub-region list does not update when changing regions.

### ISSUE THREAD

**Issue by psppwner300** [drauger-os-development/system-installer#2]
![time_zone](https://user-images.githubusercontent.com/12868939/79902830-2121d600-83e0-11ea-93db-70521fbb6db1.png)
Sub-region list does not update when changing regions.

**Comment by Batcastle** [comment]
Fixed by Commit https://github.com/drauger-os-development/system-installer/commit/90806aeb9ad660678302fb8b1e44fbc3d71f9816
