### ISSUE TITLE
Installer crash

### ISSUE THREAD

**Issue by SenlisO** [drauger-os-development/system-installer#24]
Attempt to install OS to drive fails with the following error:
(engine.py.1545): Gtk-CRITICAL **: 11:16.48.959: gtk_main_quit: assertion 'main_loops != NULL' failed
(engine.py.1545): Gtk-CRITICAL **: 11:16.50.085: gtk_main_quit: assertion 'main_loops != NULL' failed

Error occurred on both my ASUS ROG and VMware Fusion.  I sent a report on both failures.

**Comment by SenlisO** [comment]
Initial research indicated that we should be using g_application_quit() instead of gtk_main_quit().

**Comment by SenlisO** [comment]
To be clear, I was using the version of system-installer with the ISO.  I will try using the latest version from this repository and see if I get the same error.

**Comment by Batcastle** [comment]
This is not an issue. It does not affect the installation beyond making users panic. 

If you had a failed installation and saw this error, it is probably because you are using the auto partitioner which, at time of writing, is broken.

I appreciate the effort tho.

**Comment by SenlisO** [comment]
Copy all.  Sorry about that.  I was using the auto partitioner.  I was somewhat confused as to whether it was working or not.
