### ISSUE TITLE
Settings applications don't open after installation

### ISSUE THREAD

**Issue by SenlisO** [drauger-os-development/system-installer#25]
Some settings applications do not open after installation including:

Additional Drivers
Software and Updates
Software Updater
Users & Groups

**Comment by SenlisO** [comment]
Using

```bash
sudo chown 1000:1000 -R $(ls -a)
```

as suggested did not fix the issue for me.

**Comment by Batcastle** [comment]
Running that command and then running the following should fix the issue:
```
sudo apt install --reinstall dbus
```

**Comment by Batcastle** [comment]
Closing as this issue has likely been handled already. If you are still having issues, please open a new issue report.
