### ISSUE TITLE
Manual-installer how-to video tutorial

### ISSUE THREAD

**Issue by SenlisO** [drauger-os-development/system-installer#27]
Create a manual-installer how-to video tutorial to compliment the written tutorial.

**Comment by Batcastle** [comment]
Working on this. Footage has already been recorded

**Comment by Batcastle** [comment]
This has been taken care of and is up now on our YouTube: https://youtu.be/RVgiPiBS_Xw

and our Odysee: https://odysee.com/@draugerosdevelopment:a/Installing_Drauger_OS:1
