### ISSUE TITLE
Setting keyboard layout does not work

### ISSUE THREAD

**Issue by Batcastle** [drauger-os-development/system-installer#72]
Seen when setting Layout as `German` and Variant as `German (T3)`.
No error output is seen in the log file:
[system-installer.log](https://github.com/drauger-os-development/system-installer/files/8467308/system-installer.log)

`/etc/default/keyboard` has `XKBLAYOUT` and `XKBVARIANT` set to empty strings when they should be equal to `"de"` and `"T3"`. Likely data is either being lost, or thrown out by accident.

**Comment by SenlisO** [comment]
When testing in 7.5.1:

system-installer module does not honor keyboard layout if set to German and German (T3) in the installer (other variants have not been tested yet).  After the OS is installed, the keyboard layout will be English QWERTY regardless of what is set in the installer.

However, if the user enters keyboard settings, turns off use system defaults, add German T3, and remove the default US layout, the system will change to QWERTZ.  This change lasts through a restart.

**Comment by SenlisO** [comment]
Problem occurs with Dvorak layout in 7.5.1 as well

**Comment by SenlisO** [comment]
I am having trouble testing the issue in DraugerOS 7.6 as installing it in Virtmgr isn't working for me.  Would you send me the configuration you use so I can check my configuration against it?
